name: "Feature Request"
description: "Request a new feature / new functionality."
title: "[Feature]: "
labels: [
  "enhancement",
  "triage"
]
assignees:
  - "starwarsfan"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a feature request!
  - type: textarea
    id: what-happened
    attributes:
      label: "Is your feature request related to a problem?"
      description: "Please describe:"
      placeholder: "Tell us what you see!"
      value: |
        I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen:"
      placeholder: "Tell us what you see!"
      value: "..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered:"
      placeholder: "Tell us what you see!"
      value: "..."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here:"
  - type: input
    id: contact
    attributes:
      label: "Contact Details"
      description: "How can we get in touch with you if we need more info?"
      placeholder: "ex. email@example.com"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/somethi-ng/playground/blob/main/CODE_OF_CONDUCT.md)."
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
